name: CI - Maven Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11 (you can choose another version if required)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11' 
          distribution: 'temurin' 
       

      # Build and test with Maven
      - name: Build with Maven
        run: mvn clean install

      # Optionally, run tests
      - name: Run the maven
        run: mvn clean package



 
